### ISSUE TITLE
Regarding output values

### ISSUE THREAD

**Issue by rohansinghjain** [msminhas93/DeepLabv3FineTuning#8]
Hi, I've trained the model successfully. On performing inference as per code in  "analysis.ipynb", I see that the histogram of the flattened output array has a few negative values as well. How is this possible? Isn't the final output of the network obtained after a sigmoid layer so as to represent probabilities?

**Comment by rohansinghjain** [comment]
In model.py line number 9, you mention that a sigmoid activation is added after the last convolution layer. Could you please provide code pointer where this is done and if this is done, shouldn't the final outputs before thresholding have only positive values? (As stated above, I also see negative values).

**Comment by msminhas93** [comment]
@rohansinghjain the comment is wrong, I had added sigmoid but changed it to tanh. This is done in /models/segmentation/deeplabv3.py [line 37 ](https://github.com/msminhas93/DeepLabv3FineTuning/blob/0ff2682c1fe44b8fc84bfcddad47355113968b18/models/segmentation/deeplabv3.py#L37). 

![image](https://user-images.githubusercontent.com/6465972/89718715-0c694e00-d98f-11ea-80a5-20a7c90ee241.png)

**Comment by rohansinghjain** [comment]
Yes, I figured that out. Changed it to training with sigmoid and tried BCELoss, loss was not stable. Although results were good enough. Thank you.
